import { writeFileSync } from "node:fs";
import problemsJson from "../data/problems.json" with { type: "json" };
import { z } from "zod";

const TopicTag = z.object({
  name: z.string(),
  slug: z.string(),
  __typename: z.literal("CommonTagNode"),
});

const ProblemSetQuestionNodeSchema = z.object({
  difficulty: z.enum(["EASY", "MEDIUM", "HARD"]),
  id: z.number(),
  paidOnly: z.boolean(),
  questionFrontendId: z.string(),
  status: z.string(),
  title: z.string(),
  titleSlug: z.string(),
  topicTags: z.array(TopicTag),
  frequency: z.null(),
  isInMyFavorites: z.boolean(),
  acRate: z.number(),
  contestPoint: z.null(),
  __typename: z.literal("ProblemSetQuestionNode"),
});

const ProblemSetSchema = z.object({
  data: z.object({
    problemsetQuestionListV2: z.object({
      questions: z.array(ProblemSetQuestionNodeSchema),
    }),
  }),
});

// type Problem = z.infer<typeof ProblemSetQuestionNodeSchema>;

main();

function main() {
  const problems = ProblemSetSchema.parse(problemsJson);

  const output = problems.data.problemsetQuestionListV2.questions;

  const problemType = `export type Problem = {
  difficulty: "EASY" | "MEDIUM" | "HARD";
  id: number;
  paidOnly: boolean;
  questionFrontendId: string;
  status: string;
  title: string;
  titleSlug: string;
  topicTags: {
      name: string;
      slug: string;
      __typename: "CommonTagNode";
  }[];
  frequency: null;
  isInMyFavorites: boolean;
  acRate: number;
  contestPoint: null;
  __typename: "ProblemSetQuestionNode";
}`;

  const contents = [
    "// This file is AUTOGENERATED by scripts/gen.ts. DO NOT EDIT MANUALLY.",
    "",
    "// prettier-ignore",
    problemType,
    "",
    "// prettier-ignore",
    "export const ALL_PROBLEMS: Problem[] = " +
      JSON.stringify(output, null, 2) +
      ";",
    "",
  ].join("\n");

  writeFileSync("./src/gen/problems.ts", contents);
}
